#!/usr/bin/python3
# SPDX-FilecopyrigthText: 2023 Daiki Nakane
# SPDX-License-Identifier: GPL-3.0

import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(f"{ans}この数字は{'偶数' if ans % 2 == 0 else '奇数'}です",end='')
