#!/usr/bin/python3
# SPDX-FilecopyrigthText: 2023 Daiki Nakane
# SPDX-License-Identifier: GPL-3.0

import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)

if ans % 2 == 0;
    print("この数字は偶数です")
else:
    print("この数字は奇数です")
